### ISSUE TITLE
PARAGON Storm Furies sheet ?

### ISSUE THREAD

**Issue by jefftavernier** [joesinghaus/Agon-Sheet#2]
Hello,
Thanks for your work on the Agon Sheet and plugin. Could I hope the same thing for the recent Storm Furies game by John Harper ? Happy New Year :)
Jeff

**Comment by ghorbey** [comment]
Is there any plan to do it?
If not, I could do it, if the author of this sheet is ok that I start on his work.

**Comment by joesinghaus** [comment]
There are no plans. Feel free to reuse this work if it helps!
